# Generated by Django 5.2.17 on 2026-09-18 21:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('PRETEST', 'Pretest'), ('POSTEST', 'Postest')], max_length=20, unique=True, verbose_name='Tipo de Evaluación')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('instructions', models.TextField(verbose_name='Instrucciones para el Estudiante')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instrumento de Evaluación',
                'verbose_name_plural': 'Instrumentos de Evaluación',
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código de Dimensión')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Dimensión')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Dimensión de Evaluación',
                'verbose_name_plural': 'Dimensiones de Evaluación',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Enunciado de la Pregunta')),
                ('question_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Opción Múltiple'), ('TRUE_FALSE', 'Verdadero / Falso'), ('LIKERT', 'Escala Likert (Frecuencia / Acuerdo)')], default='MULTIPLE_CHOICE', max_length=20, verbose_name='Tipo de Pregunta')),
                ('weight', models.FloatField(default=1.0, verbose_name='Puntaje Máximo / Peso')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evaluations.assessment', verbose_name='Instrumento')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evaluations.dimension', verbose_name='Dimensión')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['assessment', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=350, verbose_name='Texto de la Opción')),
                ('score_value', models.FloatField(default=0.0, verbose_name='Valor / Puntaje')),
                ('is_correct', models.BooleanField(default=False, verbose_name='¿Es la opción correcta? (para conocimientos)')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='evaluations.question', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opción de Respuesta',
                'verbose_name_plural': 'Opciones de Respuesta',
                'ordering': ['question', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('PRETEST', 'Pretest'), ('POSTEST', 'Postest')], max_length=20, verbose_name='Tipo de Evaluación')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Inicio')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Finalización')),
                ('score_dimension_1', models.FloatField(default=0.0, verbose_name='Puntaje Dimensión 1 (Conocimientos)')),
                ('score_dimension_2', models.FloatField(default=0.0, verbose_name='Puntaje Dimensión 2 (Prácticas)')),
                ('total_score', models.FloatField(default=0.0, verbose_name='Puntaje Total Obtenido')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='¿Enviado y Finalizado?')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_submissions', to='evaluations.assessment', verbose_name='Instrumento')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assessments', to='accounts.studentprofile', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Evaluación de Estudiante',
                'verbose_name_plural': 'Evaluaciones de Estudiantes',
                'ordering': ['-completed_at', '-started_at'],
                'unique_together': {('student', 'assessment_type')},
            },
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_obtained', models.FloatField(default=0.0, verbose_name='Puntaje Obtenido')),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora de Respuesta')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_responses', to='evaluations.question', verbose_name='Pregunta')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_by', to='evaluations.answeroption', verbose_name='Opción Seleccionada')),
                ('student_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='evaluations.studentassessment', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Respuesta de Estudiante',
                'verbose_name_plural': 'Respuestas de Estudiantes',
                'unique_together': {('student_assessment', 'question')},
            },
        ),
    ]
