# Generated by Django 5.2.17 on 2026-09-18 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la Categoría')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='Código / Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(default='bi-shield-check', max_length=50, verbose_name='Icono Bootstrap')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría de Conocimiento',
                'verbose_name_plural': 'Categorías de Conocimiento',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del Documento')),
                ('source_institution', models.CharField(max_length=200, verbose_name='Institución / Fuente (ej. MINSA, OMS, OPS)')),
                ('publication_year', models.PositiveIntegerField(default=2024, verbose_name='Año de Publicación')),
                ('reference_url', models.CharField(blank=True, max_length=500, verbose_name='Referencia Bibliográfica o URL Oficial')),
                ('full_content', models.TextField(verbose_name='Contenido Completo del Documento')),
                ('summary', models.TextField(blank=True, verbose_name='Resumen Educativo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo para Recuperación RAG')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge.knowledgecategory', verbose_name='Categoría Principal')),
            ],
            options={
                'verbose_name': 'Documento de Conocimiento',
                'verbose_name_plural': 'Documentos de Conocimiento',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField(verbose_name='Texto del Fragmento')),
                ('keywords', models.TextField(blank=True, verbose_name='Palabras Clave / Términos de Búsqueda')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Orden dentro del Documento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgecategory', verbose_name='Categoría')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgedocument', verbose_name='Documento Origen')),
            ],
            options={
                'verbose_name': 'Fragmento de Conocimiento (RAG Chunk)',
                'verbose_name_plural': 'Fragmentos de Conocimiento (RAG Chunks)',
                'ordering': ['document', 'order'],
            },
        ),
    ]
