from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from accounts.models import User

class ExportDatasetType(models.TextChoices):
    PARTICIPANTS = 'PARTICIPANTS', _('Participantes del Estudio')
    EVALUATIONS = 'EVALUATIONS', _('Resultados de Evaluaciones (Pretest y Postest)')
    CHATBOT_USAGE = 'CHATBOT_USAGE', _('Métricas de Uso de Previene+')

class ExportFormat(models.TextChoices):
    CSV = 'CSV', _('Valores separados por comas (.csv)')
    XLSX = 'XLSX', _('Libro de Microsoft Excel (.xlsx)')

class ResearchSetting(models.Model):
    """
    Global settings for the experimental study management.
    """
    study_title = models.CharField(
        max_length=255,
        default='Efectividad del Chatbot con IA Previene+ en la Prevención de ITS en Escolares',
        verbose_name=_('Título de la Investigación')
    )
    pretest_stage_open = models.BooleanField(
        default=True,
        verbose_name=_('Etapa de Pretest Habilitada')
    )
    intervention_stage_open = models.BooleanField(
        default=True,
        verbose_name=_('Etapa de Intervención con Previene+ Habilitada')
    )
    postest_stage_open = models.BooleanField(
        default=True,
        verbose_name=_('Etapa de Postest Habilitada')
    )
    min_chat_messages_required = models.PositiveIntegerField(
        default=3,
        verbose_name=_('Mínimo de Preguntas para Completar Intervención')
    )
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _('Configuración de la Investigación')
        verbose_name_plural = _('Configuración de la Investigación')

    def __str__(self):
        return self.study_title

    @classmethod
    def get_settings(cls):
        obj, created = cls.objects.get_or_create(id=1)
        return obj

class ExportAuditLog(models.Model):
    """
    Audit log recording each export generated by researchers for traceability.
    """
    researcher = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name=_('Investigador')
    )
    dataset_type = models.CharField(
        max_length=30,
        choices=ExportDatasetType.choices,
        verbose_name=_('Conjunto de Datos')
    )
    file_format = models.CharField(
        max_length=10,
        choices=ExportFormat.choices,
        verbose_name=_('Formato')
    )
    records_count = models.PositiveIntegerField(
        default=0,
        verbose_name=_('Cantidad de Registros Exportados')
    )
    exported_at = models.DateTimeField(
        default=timezone.now,
        verbose_name=_('Fecha y Hora de Exportación')
    )

    class Meta:
        verbose_name = _('Auditoría de Exportación')
        verbose_name_plural = _('Auditorías de Exportación')
        ordering = ['-exported_at']

    def __str__(self):
        user_name = self.researcher.username if self.researcher else 'Sistema'
        return f"{self.get_dataset_type_display()} ({self.file_format}) por {user_name} - {self.exported_at.strftime('%d/%m/%Y %H:%M')}"
