# Generated by Django 5.2.17 on 2026-09-18 21:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID de Sesión')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora de Inicio')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Cierre')),
                ('total_messages', models.PositiveIntegerField(default=0, verbose_name='Total de Mensajes')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Duración Total (Segundos)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sesión Activa')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='accounts.studentprofile', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Sesión de Chatbot',
                'verbose_name_plural': 'Sesiones de Chatbot',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Estudiante'), ('assistant', 'Previene+ (IA)'), ('system', 'Sistema')], default='user', max_length=20, verbose_name='Emisor')),
                ('content', models.TextField(verbose_name='Contenido del Mensaje')),
                ('sources_used', models.TextField(blank=True, verbose_name='Fuentes Validadas Utilizadas (RAG)')),
                ('topics_detected', models.CharField(blank=True, max_length=255, verbose_name='Temáticas Detectadas')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='Tokens Consumidos')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterventionConfigLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_version', models.CharField(max_length=50, verbose_name='Versión de Previene+')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modelo de Lenguaje (OpenAI)')),
                ('temperature', models.FloatField(default=0.3, verbose_name='Temperatura de Muestreo')),
                ('system_prompt_version', models.CharField(default='v1.0-research-safe', max_length=50, verbose_name='Versión del System Prompt')),
                ('system_prompt_text', models.TextField(verbose_name='Texto del System Prompt')),
                ('knowledge_chunks_count', models.PositiveIntegerField(default=0, verbose_name='Total de Fragmentos RAG Disponibles')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_logs', to='chatbot.chatsession', verbose_name='Sesión')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_logs', to='accounts.studentprofile', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Registro de Reproducibilidad Científica',
                'verbose_name_plural': 'Registros de Reproducibilidad Científica',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
