# Generated by Django 5.2.17 on 2026-09-18 21:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_title', models.CharField(default='Efectividad del Chatbot con IA Previene+ en la Prevención de ITS en Escolares', max_length=255, verbose_name='Título de la Investigación')),
                ('pretest_stage_open', models.BooleanField(default=True, verbose_name='Etapa de Pretest Habilitada')),
                ('intervention_stage_open', models.BooleanField(default=True, verbose_name='Etapa de Intervención con Previene+ Habilitada')),
                ('postest_stage_open', models.BooleanField(default=True, verbose_name='Etapa de Postest Habilitada')),
                ('min_chat_messages_required', models.PositiveIntegerField(default=3, verbose_name='Mínimo de Preguntas para Completar Intervención')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de la Investigación',
                'verbose_name_plural': 'Configuración de la Investigación',
            },
        ),
        migrations.CreateModel(
            name='ExportAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_type', models.CharField(choices=[('PARTICIPANTS', 'Participantes del Estudio'), ('EVALUATIONS', 'Resultados de Evaluaciones (Pretest y Postest)'), ('CHATBOT_USAGE', 'Métricas de Uso de Previene+')], max_length=30, verbose_name='Conjunto de Datos')),
                ('file_format', models.CharField(choices=[('CSV', 'Valores separados por comas (.csv)'), ('XLSX', 'Libro de Microsoft Excel (.xlsx)')], max_length=10, verbose_name='Formato')),
                ('records_count', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Registros Exportados')),
                ('exported_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Exportación')),
                ('researcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Investigador')),
            ],
            options={
                'verbose_name': 'Auditoría de Exportación',
                'verbose_name_plural': 'Auditorías de Exportación',
                'ordering': ['-exported_at'],
            },
        ),
    ]
